spring.application.name=KindleSchneider-InventoryApp
spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size= 5MB

loggin:
file:
name: log/animal-registration.log
logging:
  logback:
  rollingpolicy:
  file-name-pattern: "logs/animal-registration-%d{yyyy-MM-dd}.%i.log"
    max-file-size: 10MB
    max-history: 30


